# Generated by Django 3.2.9 on 2022-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buy_tc_accpeted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='buy_tc_accpeted_date_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buy_tc_accepted',
            field=models.BooleanField(default=False, verbose_name='Buyer Terms And Conditions Accepted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buy_tc_accepted_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Buyer Terms And Conditions Accepted Time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_buy_product',
            field=models.BooleanField(default=False, verbose_name='Can Buy Product'),
        ),
    ]
