# Generated by Django 3.2.9 on 2022-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220129_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buy_tc_accepted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='buy_tc_accepted_date_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_buy_product',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sell_product',
            field=models.BooleanField(default=False, verbose_name='Can Sell Product'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_tc_accepted',
            field=models.BooleanField(default=False, verbose_name='Seller Terms And Conditions Accepted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_tc_accepted_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seller Terms And Conditions Accepted Date Time'),
        ),
    ]
