# Generated by Django 3.2.9 on 2022-02-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220206_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='title',
            field=models.CharField(choices=[('login', 'login'), ('delete', 'delete'), ('can_sell_product', 'can_sell_product')], default='login', max_length=16, unique=True, verbose_name='Title of Terms and Conditions'),
        ),
    ]
