# Generated by Django 3.2.9 on 2022-02-12 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdetails'),
        ('users', '0006_auto_20220212_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='administrative_area_level_1_short',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country_iso',
        ),
        migrations.RemoveField(
            model_name='address',
            name='formatted_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='google_place_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='route',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='utc_offset',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(default='dfgd', max_length=50, verbose_name='Place id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=2.3, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=3.3, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^\\d*$')], verbose_name='Postal Code'),
        ),
    ]
