# Generated by Django 3.2.9 on 2022-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220212_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(default='23', verbose_name='Full Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='short_address',
            field=models.TextField(default='23', verbose_name='Short Address'),
            preserve_default=False,
        ),
    ]
