# Generated by Django 3.2.9 on 2022-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220213_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
