# Generated by Django 3.2.9 on 2022-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_phoneotp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
