# Generated by Django 3.2.9 on 2022-02-25 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(default=9891232344, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^\\d*$')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
