# Generated by Django 3.2.9 on 2022-01-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_sell_product',
            field=models.BooleanField(default=False, verbose_name='Can Sell Product'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sell_tc_accpeted',
            field=models.BooleanField(default=False, verbose_name='Terms And Conditions Accepted'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
