# Generated by Django 3.2.9 on 2022-01-12 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220112_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sell_tc_accpeted',
            new_name='buy_tc_accpeted',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_sell_product',
            new_name='can_buy_product',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buy_tc_accpeted_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 12, 13, 12, 54, 354545, tzinfo=utc), verbose_name='Terms And Conditions Accepted Time'),
            preserve_default=False,
        ),
    ]
