# Generated by Django 3.2.9 on 2022-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
