# Generated by Django 3.2.9 on 2022-01-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220112_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('login', 'login'), ('delete', 'delete'), ('can_buy_product', 'can_buy_product')], default='login', max_length=15, verbose_name='Title of Terms and Conditions')),
                ('text', models.TextField(max_length=500, verbose_name='Description Of Conditional')),
            ],
        ),
    ]
