# Generated by Django 3.2.9 on 2022-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='title',
            field=models.CharField(choices=[('login', 'login'), ('delete', 'delete'), ('can_buy_product', 'can_buy_product')], default='login', max_length=15, unique=True, verbose_name='Title of Terms and Conditions'),
        ),
    ]
