# Generated by Django 3.2.9 on 2022-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220114_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_brith',
            field=models.DateField(default='2002-10-12'),
        ),
    ]
