# Generated by Django 3.2.9 on 2022-01-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_date_of_brith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='buy_tc_accpeted_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms And Conditions Accepted Time'),
        ),
    ]
