# Generated by Django 3.2.9 on 2021-12-25 10:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211225_1542'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 10, 11, 14, 120030, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram'), ('Bo', 'Box'), ('Ba', 'Bag'), ('Pi', 'Piece'), ('Li', 'Liter'), ('ml', 'ml'), ('Fe', 'Feet'), ('Ac', 'Acre')], default='Kg', max_length=9),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='fgh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='items.ItemImage'),
        ),
    ]
