# Generated by Django 3.2.9 on 2022-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_able_to_sell',
            field=models.BooleanField(default=False),
        ),
    ]
