# Generated by Django 3.2.9 on 2022-01-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_can_able_to_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expected_price',
            new_name='price',
        ),
    ]
