# Generated by Django 3.2.9 on 2022-02-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_expected_price_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
