# Generated by Django 3.2.9 on 2022-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembag',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
