# Generated by Django 3.2.9 on 2022-02-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itembag_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
