# Generated by Django 3.2.9 on 2022-02-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_auto_20220211_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reply_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_replies', to='items.itemrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
