# Generated by Django 3.2.9 on 2022-02-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_sellerreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerreply',
            name='reply_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_replies', to='items.itemrating'),
        ),
    ]
