# Generated by Django 3.2.9 on 2022-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20220111_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('primary', 'blue'), ('secondary', 'purple'), ('danger', 'red'), ('info', 'lightblue'), ('warning', 'yellow'), ('dark', 'black'), ('default', 'default')], default='default', max_length=9),
        ),
    ]
