# Generated by Django 3.2.9 on 2022-01-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20220112_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to='items.item'),
        ),
    ]
