# Generated by Django 3.2.9 on 2022-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20220226_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categorytype',
            new_name='category_type',
        ),
    ]
