# Generated by Django 3.2.9 on 2022-01-13 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0012_alter_itemrating_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemrating',
            unique_together={('user', 'item')},
        ),
    ]
