# Generated by Django 3.2.9 on 2022-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_rename_categorytype_item_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
            preserve_default=False,
        ),
    ]
