# Generated by Django 3.2.9 on 2022-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_itemrating_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrating',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='itemrating',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
