# Generated by Django 3.2.9 on 2022-01-19 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20220117_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_unit', models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram'), ('Bo', 'Box'), ('Ba', 'Bag'), ('Pi', 'Piece'), ('Li', 'Liter'), ('ml', 'ml'), ('Fe', 'Feet'), ('Ac', 'Acre')], default='Kg', max_length=9)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='items.item')),
            ],
        ),
    ]
