# Generated by Django 3.2.9 on 2022-02-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-average_rating', '-created')},
        ),
        migrations.AlterModelOptions(
            name='itembag',
            options={'ordering': ('price', '-created')},
        ),
        migrations.AlterModelOptions(
            name='itemrating',
            options={'ordering': ('-created', '-rating')},
        ),
        migrations.AlterField(
            model_name='item',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
