# Generated by Django 3.2.9 on 2022-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20220228_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembag',
            options={'ordering': ('price',)},
        ),
    ]
