# Generated by Django 3.2.9 on 2022-01-19 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0016_auto_20220119_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to='users.user'),
            preserve_default=False,
        ),
    ]
