# Generated by Django 3.2.9 on 2022-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_itemrating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_date',
        ),
        migrations.AddField(
            model_name='item',
            name='available_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itembag',
            name='whole_item_bag',
            field=models.BooleanField(default=False),
        ),
    ]
