# Generated by Django 3.2.9 on 2022-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_item_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembag',
            name='whole_item_bag',
        ),
        migrations.AddField(
            model_name='itembag',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
    ]
