# Generated by Django 3.2.9 on 2022-01-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20220120_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram')], default='Kg', max_length=9),
        ),
        migrations.AlterField(
            model_name='itembag',
            name='quantity_unit',
            field=models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram')], default='Kg', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='itembag',
            unique_together={('item', 'quantity', 'quantity_unit', 'price')},
        ),
    ]
