# Generated by Django 3.2.9 on 2022-01-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
