# Generated by Django 3.2.9 on 2022-01-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_current_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_unit',
            field=models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram'), ('Bo', 'Box'), ('Ba', 'Bag'), ('Pi', 'Piece'), ('Li', 'Liter'), ('ml', 'ml'), ('Fe', 'Feet'), ('Ac', 'Acre')], default='Kg', max_length=9),
        ),
    ]
