# Generated by Django 3.2.9 on 2022-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='verified_phone_number',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(choices=[('OP', 'NetBanking Payment'), ('COD', 'Cash On Delivery'), ('UP', 'UPI Payment')], default='OP', max_length=3),
        ),
    ]
