# Generated by Django 3.2.9 on 2022-02-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_phoneotp_is_verified'),
        ('orders', '0004_auto_20220213_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
