# Generated by Django 3.2.9 on 2022-01-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220118_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_unit',
            field=models.CharField(choices=[('To', 'Ton'), ('Kg', 'Kg'), ('Gr', 'Gram')], default='Kg', max_length=9),
        ),
    ]
