# Generated by Django 3.2.9 on 2022-02-19 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
