# Generated by Django 3.2.9 on 2022-02-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220219_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_order',
        ),
    ]
