# Generated by Django 3.2.9 on 2022-02-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_current_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ('updated',), 'verbose_name': 'order details', 'verbose_name_plural': 'order details'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-updated',)},
        ),
    ]
